hl.define_submap("note", function()
    hl.bind("S", hl.dsp.workspace.toggle_special("note"))
    hl.bind("SHIFT + S", hl.dsp.window.move({ workspace = "special:note" }))
    hl.bind("V", hl.dsp.exec_cmd("~/.local/bin/inbox.sh -c"))
    hl.bind("M", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[floatui memo]])) end)
    hl.bind("I", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[kitty --class floating --title "Pop-up Terminal" -e ~/.local/bin/inbox]])) end)
    hl.bind("SHIFT + I", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[kitty --class floating --title "Pop-up Terminal" -e ~/.local/bin/inbox -n]])) end)
    hl.bind("L", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[kitty --class floating --title "Pop-up Terminal" -e ~/.local/bin/inbox -l]])) end)
    hl.bind("O", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[obsidian]])) end)
    hl.bind("D", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[kitty nvim ~/notes/Journal/Entries/Daily/$(date +"%F").md]])) end)
    hl.bind("T", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[kitty --class floating --title "Pop-up Terminal" -e ~/.local/bin/todo]])) end)
    hl.bind("SUPER + N", hl.dsp.submap("reset"))
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.define_submap("group", function()
    hl.bind("G", hl.dsp.group.toggle())
    hl.bind("SHIFT + G", hl.dsp.group.lock({ action = "toggle" }))
    hl.bind("ALT + U", hl.dsp.group.move_window({ direction = "out" }))
    hl.bind("ALT + H", hl.dsp.group.move_window({ direction = "left" }))
    hl.bind("ALT + L", hl.dsp.group.move_window({ direction = "right" }))
    hl.bind("ALT + K", hl.dsp.group.move_window({ direction = "up" }))
    hl.bind("ALT + J", hl.dsp.group.move_window({ direction = "down" }))
    hl.bind("H", hl.dsp.group.prev())
    hl.bind("L", hl.dsp.group.next())
    hl.bind("left", hl.dsp.group.prev())
    hl.bind("right", hl.dsp.group.next())
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
end)

hl.define_submap("resize", function()
    hl.bind("right", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 100, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -100, relative = true }), { repeating = true })
    hl.bind("SHIFT + right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("SHIFT + up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
    hl.bind("SUPER + R", hl.dsp.submap("reset"))
end)

hl.define_submap("screen", function()
    hl.bind("a", hl.dsp.exec_cmd("hyprshot -m region --freeze"))
    hl.bind("w", hl.dsp.exec_cmd("hyprshot -m window --freeze"))
    hl.bind("m", hl.dsp.exec_cmd("hyprshot -m output --freeze"))
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
    hl.bind("SUPER + R", hl.dsp.submap("reset"))
end)

hl.define_submap("files", function()
    hl.bind("D", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[nemo ~/Downloads/]])) end)
    hl.bind("M", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[nemo ~/Music/]])) end)
    hl.bind("V", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[nemo ~/Videos/]])) end)
    hl.bind("P", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[nemo ~/Pictures/]])) end)
    hl.bind("W", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[nemo ~/Documents/]])) end)
    hl.bind("C", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[nemo ~/code/]])) end)
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.define_submap("code", function()
    hl.bind("D", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[zeditor ~/code/dotfiles/]])) end)
    hl.bind("B", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[zeditor ~/code/blog/]])) end)
    hl.bind("C", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[zeditor ~/code/]])) end)
    hl.bind("SHIFT + D", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[kitty -e nvim ~/code/dotfiles/]])) end)
    hl.bind("SHIFT + B", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[kitty -e nvim ~/code/blog/]])) end)
    hl.bind("SHIFT + C", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[kitty -e nvim ~/code/]])) end)
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.define_submap("apps", function()
    hl.bind("M", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[mpv --idle --force-window]])) end)
    hl.bind("SHIFT + M", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[cinny]])) end)
    hl.bind("S", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[spotify-launcher]])) end)
    hl.bind("SHIFT + S", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[signal-desktop]])) end)
    hl.bind("P", function() hl.dispatch(hl.dsp.submap("reset")); hl.dispatch(hl.dsp.exec_cmd([[zathura]])) end)
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.unbind("CTRL, D")

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, locked = true })
hl.bind("SHIFT + XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 10%+"), { repeating = true, locked = true })
hl.bind("SHIFT + XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 10%-"), { repeating = true, locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("SUPER + XF86AudioMute", hl.dsp.exec_cmd("noctalia-shell ipc call volume openPanel"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { repeating = true, locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { repeating = true, locked = true })
hl.bind("SHIFT + XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 10%+"), { repeating = true, locked = true })
hl.bind("SHIFT + XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"), { repeating = true, locked = true })
hl.bind("SUPER + R", hl.dsp.exec_cmd("~/.local/bin/wm-reload"))
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.close())
hl.bind("XF86AudioMedia", hl.dsp.exec_cmd("noctalia-shell ipc call controlCenter toggle"))
hl.bind("SHIFT + XF86AudioMedia", hl.dsp.exec_cmd("noctalia-shell ipc call sessionMenu toggle"))
hl.bind("SUPER + D", hl.dsp.exec_cmd("noctalia-shell ipc call launcher toggle"))
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("fuzzel"))
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only --freeze"))
hl.bind("SUPER + Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))
hl.bind("SUPER + period", hl.dsp.exec_cmd("BEMOJI_PICKER_CMD='wofi -d --hide-scroll --width=350 --location=center' bemoji -n -e | wl-copy"))
hl.bind("SUPER + SHIFT + period", hl.dsp.exec_cmd("jome | wl-copy"))
hl.bind("SUPER + CTRL + period", hl.dsp.exec_cmd("(FZF_DEFAULT_OPTS='' unipicker --copy-command wl-copy --command 'wofi -d') | wl-copy"))
hl.bind("SUPER + CTRL + E", hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind("SUPER + V", hl.dsp.exec_cmd("noctalia-shell ipc call plugin:clipboard toggle"))
hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))
hl.bind("SUPER + ALT + W", hl.dsp.exec_cmd("waypaper"))
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("floatui memo"))
hl.bind("SUPER + XF86AudioMedia", hl.dsp.exec_cmd("floatui memo"))
hl.bind("SUPER + escape", hl.dsp.exec_cmd("~/.config/hypr/scripts/quick_settings.py"))
hl.bind("SUPER + B", hl.dsp.exec_cmd("firefox"))
hl.bind("SUPER + CTRL + B", hl.dsp.exec_cmd("firefox --private-window"))
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("qutebrowser"))
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd("ghostty"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("nemo"))
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("kitty -e yazi $HOME"))
hl.bind("SUPER + O", hl.dsp.exec_cmd("obsidian"))
hl.bind("SUPER + C", hl.dsp.exec_cmd("zeditor"))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("speedcrunch"))
hl.bind("SUPER + M", hl.dsp.exec_cmd("1password"))
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("enteauth"))
hl.bind("SUPER + T", hl.dsp.exec_cmd("todoist"))
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("floatui todo"))
hl.bind("SUPER + CTRL + T", hl.dsp.exec_cmd("korganizer"))
hl.bind("SUPER + CTRL + Z", hl.dsp.exec_cmd("typora"))
hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd("zathura"))
hl.bind("SUPER + XF86AudioPlay", hl.dsp.exec_cmd("spotify-launcher"))
hl.bind("SUPER + SHIFT + XF86AudioPlay", hl.dsp.exec_cmd("kitty -e kew"))
hl.bind("SUPER + CTRL + XF86AudioPlay", hl.dsp.exec_cmd("mpv --idle --force-window"))

hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
hl.bind("SUPER + SHIFT + down", hl.dsp.window.move({ direction = "down" }))
hl.bind("SUPER + CTRL + left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })
hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "right" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "down" }))

hl.bind("SUPER + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + SHIFT + F", hl.dsp.window.pin())
hl.bind("SUPER + CTRL + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind("SUPER + ALT + F", hl.dsp.exec_cmd("killall -SIGUSR1 waybar"))
hl.bind("SUPER + CTRL + W", hl.dsp.exec_cmd("~/.config/hypr/scripts/zen-mode.sh"))

hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind("SUPER + CTRL + S", hl.dsp.workspace.toggle_special("magic2"))
hl.bind("SUPER + CTRL + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic2" }))
hl.bind("SUPER + ALT + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + ALT + left", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + ALT + L", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + ALT + H", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + CTRL + Tab", hl.dsp.exec_cmd("noctalia-shell ipc call plugin:workspace-overview toggle"))
hl.bind("SUPER + Tab", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + ALT + Return", hl.dsp.workspace.toggle_special("term-scratchpad"))

hl.bind("SUPER + N", hl.dsp.submap("note"))
hl.bind("SUPER + SHIFT + N", hl.dsp.workspace.toggle_special("note"))
hl.bind("SUPER + SHIFT + G", hl.dsp.submap("group"))
hl.bind("SUPER + SHIFT + R", hl.dsp.submap("resize"))
hl.bind("SUPER + SHIFT + Print", hl.dsp.submap("screen"))
hl.bind("SUPER + CTRL + E", hl.dsp.submap("files"))
hl.bind("SUPER + CTRL + C", hl.dsp.submap("code"))
hl.bind("SUPER + CTRL + D", hl.dsp.submap("apps"))

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

for i = 1, 9 do
    hl.bind("SUPER + " .. i, hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. i, hl.dsp.window.move({ workspace = i, silent = true }))
end
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10, silent = true }))

for i = 11, 19 do
    hl.bind("SUPER + F" .. (i - 10), hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + F" .. (i - 10), hl.dsp.window.move({ workspace = i, silent = true }))
end