hl.window_rule({ match = { class = "^(kitty)$" }, opacity = "0.95 0.9" })
hl.window_rule({ match = { class = "^(floating)$" }, float = true, size = "700 450", center = true })
hl.window_rule({ match = { class = "^(swappy)$" }, float = true })
hl.window_rule({ match = { class = "^(waypaper)$" }, float = true })
hl.window_rule({ match = { class = "^(org.gnome.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(speedcrunch)$" }, float = true })
hl.window_rule({ match = { class = "^(imv)$" }, float = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, float = true })
hl.window_rule({ match = { class = "^(org.kde.polkit-kde-authentication-agent-1)$" }, float = true })
hl.window_rule({ match = { title = "^(Pop-up Terminal)$" }, float = true, size = "1000 650", center = true })

hl.window_rule({ match = { class = ".*" }, suppress_event = "maximize" })
hl.window_rule({ match = { class = "^(term-scratchpad)$" }, workspace = "special:term-scratchpad", size = "1200 800", center = true })
hl.window_rule({ match = { class = "^(quick-settings)$" }, float = true, size = "500 700", move = "100%-520 50", pin = true })
hl.window_rule({ match = { class = "^(noctalia-shell)$", title = "^(launcher)$" }, float = true, size = "100% 100%", move = "0 0", pin = true, no_anim = true })
hl.window_rule({ match = { class = "^(cinny)$" }, float = true, workspace = "9" })
hl.window_rule({ match = { class = "^(spotify-launcher)$" }, workspace = "10" })
hl.window_rule({ match = { class = "^(pocket-casts-desktop)$" }, workspace = "10" })
hl.window_rule({ match = { title = "^(kew)$" }, workspace = "10" })
hl.window_rule({ match = { class = "^(com.github.th_ch.youtube_music)$" }, float = true, workspace = "10", size = "1200 800", center = true })

hl.window_rule({ match = { class = "^(obsidian)$" }, float = true, size = "1400 900", center = true })
hl.window_rule({ match = { class = "^(todoist)$" }, float = true, size = "1000 800", center = true })
hl.window_rule({ match = { class = "^(korganizer)$" }, float = true, size = "1200 800", center = true })
hl.window_rule({ match = { class = "^(typora)$" }, float = true, size = "1200 900", center = true })
hl.window_rule({ match = { class = "^(org.pwmt.zathura)$" }, float = true, size = "1000 1200", center = true })
hl.window_rule({ match = { class = "^(okular)$" }, float = true, size = "1000 1200", center = true })
hl.window_rule({ match = { class = "^(enteauth)$" }, float = true, size = "400 700", center = true })
hl.window_rule({ match = { class = "^(1Password)$" }, float = true, size = "1000 700", center = true })
hl.window_rule({ match = { title = "^(floating)$" }, float = true, size = "1000 700", center = true })

hl.window_rule({ match = { class = "^(obsidian)$" }, workspace = "special:note" })
hl.window_rule({ match = { class = "^(typora)$" }, workspace = "special:note" })
hl.window_rule({ match = { class = "^(todoist)$" }, workspace = "special:note" })
hl.window_rule({ match = { class = "^(korganizer)$" }, workspace = "special:note" })

hl.workspace_rule({ workspace = "special:term-scratchpad", on_created_empty = "kitty --class term-scratchpad" })