color0 #131314
color1 #ffb4ab
color2 #c4c6d4
color3 #c7c6cc
color4 #d5c1cd
color5 #c4c6d4
color6 #c7c6cc
color7 #e5e2e2
color8 #909096
color9 #ffb4ab
color10 #c4c6d4
color11 #c7c6cc
color12 #d5c1cd
color13 #c4c6d4
color14 #c7c6cc
color15 #e5e2e2

cursor                #e5e2e2
cursor_text_color     #131314
background            #131314
foreground            #e5e2e2
selection_foreground  #c7c6cc
selection_background  #46464b
active_border_color   #c4c6d4
inactive_border_color #46464b
url_color             #c4c6d4
