$primary = rgb(e4c18e)
$surface = rgb(16130f)
$secondary = rgb(d6c4ab)
$error = rgb(ffb4ab)
$tertiary = rgb(c0cc9b)
$surface_lowest = rgb(100e0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
