customCommands:
  - key: '<delete>'
    context: 'files'
    command: 'git update-index --assume-unchanged {{.SelectedFile.Name}}'
  - key: 'Q'
    context: 'global'
    command: 'exit'
  - key: "M"
    command: "git mergetool {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening mergetool"
    subprocess: true
  - key: 'O'
    context: 'global'
    command: 'nemo .'
