$primary = rgb(94d69e)
$surface = rgb(111411)
$secondary = rgb(b2ceb3)
$error = rgb(ffb4ab)
$tertiary = rgb(a7c8ff)
$surface_lowest = rgb(0b0f0c)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
