$primary = rgb(ffb3b0)
$surface = rgb(1a1110)
$secondary = rgb(f9b5b2)
$error = rgb(ffb4ab)
$tertiary = rgb(ffb960)
$surface_lowest = rgb(150c0b)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
