$primary = rgb(b3c8e5)
$surface = rgb(121315)
$secondary = rgb(c0c7d3)
$error = rgb(ffb4ab)
$tertiary = rgb(ddbcdc)
$surface_lowest = rgb(0d0e10)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
