- name: Dev Tools
  become: yes
  pacman:
    name:
      - kitty
      - neovim
      - zellij # better tmux
      - bat # better cat
      - htop # better htop
      - lazygit
      - zoxide # better cd command
      - fzf
      - yazi # better ranger (cli file manager)
      - ripgrep
    state: present

- name: Languages & Compilers
  become: yes
  pacman:
    name:
      - clang
      - gcc
      - rust
    state: present

- name: Development Flatpaks
  community.general.flatpak:
    name:
      - md.obsidian.Obsidian
      - com.axosoft.GitKraken
      - org.speedcrunch.SpeedCrunch
