- name: Install Hyprland and needed pac
  become: yes
  pacman:
    name:
      - hyprland
      - hyprpaper
      - hyprlock
      - hypridle
      - waybar
      - rofi
      - flameshot
    state: present


- name: Yay Packages
  become: no # maybe yes
  ansible.builtin.command: "yay -S wlogout"

- name: Additional packages to look cool
  become: yes
  pacman:
    name:
      - kitty
      - neovim
      - zellij # better tmux
      - bat # better cat
      - htop # better htop
      - lazygit
      - zoxide # better cd command
      - fzf
      - ripgrep
    state: present
