---
- name: Main Setup File
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: "hyprland"
      prompt: "Do you want to install Hyprland (yes/no)?"
      private: no

    - name: "dev_setup"
      prompt: "Do you want to install the development setup (yes/no)?"
      private: no

    - name: "office_setup"
      prompt: "Do you want to install the office setup (yes/no)?"
      private: no

    - name: "clone_dots"
      prompt: "Do you want to clone the dotfiles (yes/no)?"
      private: no

  tasks:
    - name: Install needed general Tools
      become: yes
      pacman:
        name:
          - flatpak
        state: present

    - include_tasks: hyprland.yml
      when: hyprland | bool

    - include_tasks: dev.yml
      when: dev_setup | bool

    - include_tasks: office.yml
      when: office_setup | bool

    - name: Clone or update the Git repository
      git:
        repo: "git@github.com:bitSheriff/dotfiles.git"
        dest: "~/.config"
        version: master # Setze die gewünschte Branch oder Tag, wenn benötigt
        force: yes # Benutze die Option force, um das Repository zu überschreiben
      when: clone_dots | bool
